#!/usr/bin/env bash
# TOY Office - Font preparation script (macOS/Linux)
# Downloads Liberation Sans/Serif/Mono + Carlito, copies TTFs, generates AllFonts.js
# Equivalent of prepare-fonts.ps1 for non-Windows platforms.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FONTS_DIR="$PROJECT_ROOT/src/fonts"
ALLFONTS_PATH="$PROJECT_ROOT/src/sdkjs/common/AllFonts.js"
TEMP_DIR="${TMPDIR:-/tmp}/euro-office-fonts"

LIBERATION_URL="https://github.com/liberationfonts/liberation-fonts/files/7261482/liberation-fonts-ttf-2.1.5.tar.gz"
CARLITO_URL_BASE="https://github.com/googlefonts/carlito/raw/main/fonts/ttf"

echo ""
echo "=== TOY Office - Font Preparation ==="

# 1. Download Liberation fonts
mkdir -p "$TEMP_DIR"
TAR_GZ="$TEMP_DIR/liberation-fonts.tar.gz"

if [ ! -f "$TAR_GZ" ]; then
    echo "[1/6] Downloading Liberation fonts..."
    curl -L -o "$TAR_GZ" "$LIBERATION_URL"
else
    echo "[1/6] Using cached Liberation download..."
fi

# 2. Extract
echo "[2/6] Extracting Liberation fonts..."
EXTRACT_DIR="$TEMP_DIR/extracted"
rm -rf "$EXTRACT_DIR"
mkdir -p "$EXTRACT_DIR"
tar -xzf "$TAR_GZ" -C "$EXTRACT_DIR"

TTF_DIR=$(find "$EXTRACT_DIR" -type d -name "liberation-fonts-ttf-*" | head -1)
if [ -z "$TTF_DIR" ]; then
    echo "ERROR: Could not find extracted font directory"
    exit 1
fi

# 3. Download Carlito fonts
echo "[3/6] Downloading Carlito fonts..."
CARLITO_DIR="$TEMP_DIR/carlito"
mkdir -p "$CARLITO_DIR"

CARLITO_FILES=("Carlito-Regular.ttf" "Carlito-Italic.ttf" "Carlito-Bold.ttf" "Carlito-BoldItalic.ttf")
for cf in "${CARLITO_FILES[@]}"; do
    dest="$CARLITO_DIR/$cf"
    if [ ! -f "$dest" ]; then
        echo "  Downloading: $cf"
        curl -L -o "$dest" "$CARLITO_URL_BASE/$cf"
    else
        echo "  Cached: $cf"
    fi
done

# 4. Copy all TTF files to src/fonts/
echo "[4/6] Copying fonts..."
mkdir -p "$FONTS_DIR"

LIBERATION_FILES=(
    "LiberationSans-Regular.ttf" "LiberationSans-Italic.ttf"
    "LiberationSans-Bold.ttf" "LiberationSans-BoldItalic.ttf"
    "LiberationSerif-Regular.ttf" "LiberationSerif-Italic.ttf"
    "LiberationSerif-Bold.ttf" "LiberationSerif-BoldItalic.ttf"
    "LiberationMono-Regular.ttf" "LiberationMono-Italic.ttf"
    "LiberationMono-Bold.ttf" "LiberationMono-BoldItalic.ttf"
)

for f in "${LIBERATION_FILES[@]}"; do
    cp "$TTF_DIR/$f" "$FONTS_DIR/$f"
    echo "  Copied: $f"
done

for f in "${CARLITO_FILES[@]}"; do
    cp "$CARLITO_DIR/$f" "$FONTS_DIR/$f"
    echo "  Copied: $f"
done

# 5. Generate AllFonts.js
echo "[5/6] Generating AllFonts.js..."

ALL_FILES=(
    "${LIBERATION_FILES[@]}"
    "${CARLITO_FILES[@]}"
)

# Build __fonts_files array
FILES_JSON=""
for i in "${!ALL_FILES[@]}"; do
    if [ "$i" -gt 0 ]; then FILES_JSON+=", "; fi
    FILES_JSON+="\"${ALL_FILES[$i]}\""
done

# Font family index mapping (0-based indices into ALL_FILES)
# Liberation Sans: 0-3, Liberation Serif: 4-7, Liberation Mono: 8-11, Carlito: 12-15
cat > "$ALLFONTS_PATH" << 'HEREDOC_EOF'
// Generated by scripts/prepare-fonts.sh -- do not edit manually.
HEREDOC_EOF

cat >> "$ALLFONTS_PATH" << EOF
window["__fonts_files"] = [$FILES_JSON];
window["__fonts_infos"] = [
    ["Liberation Sans", 0, 0, 1, 0, 2, 0, 3, 0],
    ["Liberation Serif", 4, 0, 5, 0, 6, 0, 7, 0],
    ["Liberation Mono", 8, 0, 9, 0, 10, 0, 11, 0],
    ["Carlito", 12, 0, 13, 0, 14, 0, 15, 0],
    ["Arial", 0, 0, 1, 0, 2, 0, 3, 0],
    ["Helvetica", 0, 0, 1, 0, 2, 0, 3, 0],
    ["Times New Roman", 4, 0, 5, 0, 6, 0, 7, 0],
    ["Courier New", 8, 0, 9, 0, 10, 0, 11, 0],
    ["Calibri", 12, 0, 13, 0, 14, 0, 15, 0],
    ["Cambria", 4, 0, 5, 0, 6, 0, 7, 0]
];
window["g_fonts_selection_bin"] = "";
EOF

# 6. Generate font thumbnail sprites
echo "[6/6] Generating font thumbnail sprites..."
SPRITE_SCRIPT="$PROJECT_ROOT/scripts/generate-font-sprite.py"
if [ -f "$SPRITE_SCRIPT" ]; then
    python3 "$SPRITE_SCRIPT"
else
    echo "WARNING: generate-font-sprite.py not found, skipping sprite generation"
fi

echo ""
echo "=== Font preparation complete ==="
echo "Fonts in: $FONTS_DIR"
echo "AllFonts.js updated: $ALLFONTS_PATH"
echo ""
